name = "envelopes"
version = "0.1.0"
license = "license"
author = "Federico E. Benelli"
maintainer = "fedebenelli@outlook.com"
copyright = "Copyright 2023, Federico E. Benelli"

[build]
link = "lapack"
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
ftools = {git = "https://github.com/fedebenelli/ftools"}

[fortran]
implicit-external = true  # default: false
implicit-typing = true  # default: false
